### ISSUE TITLE
Miner hash rate reporting error

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1173]
### What happened?

Miner reporting not correct hash-rate, could be ridiculously high with more than NPROC threads

### Version

0.1.27

### Relevant log output

```shell
Baseline: on a 24C48T system, using 1 thread


new work xx 0 0 H/s
new work xx 1 2.21 MH/s
new work xx 2 2.20 MH/s
new work xx 3 2.21 MH/s
```

using 4 thread

```
new work xx 1 33.44 MH/s
new work xx 2 32.65 MH/s
new work xx 3 32.52 MH/s
new work xx 4 33.39 MH/s
```
That's 16x of baseline

using 128 threads
```
new work xx 1 7.97 GH/s
new work xx 2 8.12 GH/s
new work xx 3 8.18 GH/s
new work xx 4 6.16 GH/s
```
Sounds like the hash rate result is redundantly multiplied by number of threads
```


### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by mat-if** [comment]
Ah, good catch, thank you. I forgot to divide the work done by the thread count. Should be fixed in #1174

**Comment by QustomQure** [comment]
@mat-if Not fixed still in 0.1.28 I have something like 20GH if i put 180 threads

**Comment by terrancewong** [comment]
might be a 'clock' issue, should use 'wall clock' instead of 'cputime'

**Comment by mat-if** [comment]
Ah, good catch. I missed it when looking over whether we needed to bump our rust package, so it didn't get fully released via NPM. It should get released in 0.1.29

**Comment by mat-if** [comment]
This should be fixed now for all installation types in version [0.1.29](https://github.com/iron-fish/ironfish/releases/tag/v0.1.29), feel free to bring this back up if it's still an issue

**Comment by QustomQure** [comment]
Yes it is working like in previous versions. Same hashrate in all threads(32) and any other big number, 128 for example
