### ISSUE TITLE
Account Balance wrong

### ISSUE THREAD

**Issue by hodls** [iron-fish/ironfish#501]
My accounts balance is different from available, for no reason, I have not made payments yet

**Comment by georeith** [comment]
This is my screenshot 🤔 

https://discord.com/channels/771503434028941353/816795916627345450/915698504280707114

https://github.com/iron-fish/ironfish/issues/502

**Comment by hodls** [comment]
Wrong screenshot, lol, I had the same issue and was comparing

**Comment by hodls** [comment]
I fixed it btw by restarting node

**Comment by georeith** [comment]
@hodls ah interesting, just tried restarting and the issue still persists for me

**Comment by hodls** [comment]
strange... reset the node right, not only the miner?

**Comment by georeith** [comment]
Yeah definitely the node

**Comment by hodls** [comment]
Yes, my issue is persisting. See https://github.com/iron-fish/ironfish/issues/505 @georeith
